### ISSUE TITLE
Node Properties not working

### ISSUE THREAD

**Issue by jochen1234** [psyntium/node-red-contrib-http-request-multipart#1]
Properties are shown in the actual version because

data-template-name="www-request"
data-help-name="www-request"

are wrong, correct is

data-template-name="www-request-multipart"
data-help-name="www-request-multipart"

I fix it and add a label to each 
[www-request-multipart.html.txt](https://github.com/psyntium/node-red-contrib-http-request-multipart/files/1730797/www-request-multipart.html.txt)
properties.

**Comment by gesbaby** [comment]
I have the same issue.  The node can't be configured. The properties window is empty.

**Comment by source-creator** [comment]
Same here

**Comment by jochen1234** [comment]
What is the process to get this fixed? I am not allowed to check in this change.

**Comment by napomd** [comment]
I am experiencing the same problem. Any solution?

**Comment by psyntium** [comment]
sorry.. just noticed the bug.. it is fixed now
